### ISSUE TITLE
OCSP stapling and SPDY on Akamai?

### ISSUE THREAD

**Issue by cristim** [igrigorik/istlsfastyet.com#58]
What is it needed to configure OCSP stapling and SPDY on Akamai?

The website I am working on consumes quite a few APIs that I know use Akamai, and I am quite positive these features are not in place, at least as per http://www.webpagetest.org/result/141205_KM_29b3d5e1a20891c168cc19b8633532a3/

Anyone has experience with getting it configured, so I can raise this to my colleagues who maintain those APIs?

**Comment by vigneshshanmugam** [comment]
SPDY on Akamai CDN cannot be enabled unless you are a premium customer of them. 

Not sure about OCSP stapling.

**Comment by guypod** [comment]
That's incorrect. SPDY is not a premium offering on Akamai. It may require some new paperwork, because of some legal tidbits, but not an extra charge.

It's possible some specific older Akamai products don't support it, but that's due to technology reasons (i.e. we haven't back-ported SPDY to all the older software stacks).

**Comment by vigneshshanmugam** [comment]
@guypod : Sorry for that. But this was told by one of the account team member of Akamai. 

Can you confirm whether this domain img1a.flixcart.com can be configured to support SPDY?.

**Comment by guypod** [comment]
@vigneshshanmugam Let's take this offline - I'll send you an email separately.

**Comment by cristim** [comment]
@guypod all those with *.base.maps.api.here.com are definitely served by Akamai.

We started a conversation with our contacts from Akamai about OCSP stapling and it seems not supported yet, can you confirm this? I will ask them about SPDY as well.

**Comment by cristim** [comment]
It turns out OCSP stapling is actually available for us but we can't just enable it so easily since our configuration is shared by multiple domains and enabling it for one for testing would change them all(including some production ones) so we can't really test it first without impacting production, and we're stuck for now because of this.

At least for us, SPDY/HTTP2.0 is not available at all, but it's off course on a roadmap.

@igrigorik perhaps you should update the CDN table to make it more clear that the Akamai implementation of these features can to be tricky in some cases, so people can be aware of this when evaluating CDN providers.

**Comment by sludin** [comment]
Christian,

As SPDY has been termed ‘experimental’ form the beginning it is not
available by default.  You need to join the SPDY ‘beta’ in order to activate
it.  If you contact your rep at Akamai they should be able to arrange that.
If you run into any sort of blocker, or do not have a clear person to
contact let me know and I will assist.  Note that it is expected that SPDY
will go away with h2 fully in its place in the next 12 months.

As for h2, it is active across our network right now.  This is planned to be
put into general availability for everyone using TLS by the end of the year
as an opt-out.  In the mean time you can have it activated (opt-in) as part
of the h2 beta ( same do-si-do as SPDY, same caveat to contact me ).

Getting these turned on should be no trickier than any other Akamai feature.

There is one caveat currently: Our ‘re-rollout’ of ALPN is almost complete,
but there are still some Akamai region where it is not active.  No ALPN in a
region effectively means no SPDY/h2 for Chrome/Firefox in that region.  The
reactivation of ALPN across the network is expected to be complete in the
next few weeks.  

For a good example of an h2 site you can checkout https://letsencrypt.org.

-stephen

From:  Cristian Măgherușan-Stanciu <notifications@github.com>
Reply-To:  "igrigorik/istlsfastyet.com"
<reply+002159036dd0160a0db80580380f7b8a54dc2265369b67e892cf00000001111da8dc9
2a169ce030c4a4c@reply.github.com>
Date:  Sunday, March 15, 2015 at 1:09 PM
To:  "igrigorik/istlsfastyet.com" <istlsfastyet.com@noreply.github.com>
Cc:  Stephen Ludin <sludin@ludin.org>
Subject:  Re: [istlsfastyet.com] OCSP stapling and SPDY on Akamai? (#58)

**Comment by jakajancar** [comment]
FYI, we were told SPDY/HTTP2 is not available today on our Object Delivery products. We would need to upgrade to Akamai Ion / "web experience" products, which is several times more expensive. We were told it's coming to all products in December 2014.

//cc @sludin @guypod

**Comment by sludin** [comment]
I believe that to be inaccurate assuming your product is a secure delivery
product (over TLS) with a certificate specific to your domain.  Please
contact me off of the list so I can help you look into the matter.  At the
very least the answer should be, 'it is coming.'

-stephen
sludin@akamai.com


From:  Jaka Janèar <notifications@github.com>
Reply-To:  "igrigorik/istlsfastyet.com"
<reply+002159035de6ab0ca8470a9917cbd4fcb501950e13a392ff92cf00000001112ec4d39
2a169ce030c4a4c@reply.github.com>
Date:  Saturday, March 28, 2015 at 3:36 PM
To:  "igrigorik/istlsfastyet.com" <istlsfastyet.com@noreply.github.com>
Cc:  Stephen Ludin <sludin@ludin.org>
Subject:  Re: [istlsfastyet.com] OCSP stapling and SPDY on Akamai? (#58)

**Comment by javiergarza** [comment]
@michaelhood Akamai does support OCSP for a couple of months now. I have seen two large sites delivered by Akamai that already have OCSP stapling on the Akamai delivered certificate.

AFAIK the Akamai's Certificate Provisioning System (CPS) allows enabling OCSP on the certificate. Please check the Akamai Community site at https://community.akamai.com/ for more details as those kind of announcements can be seeing there earlier than on Akamai's corporate site

**Comment by michaelhood** [comment]
thanks @javiergarza - I'll have to follow up with support. We do use CPS but I've not seen this option available.

**Comment by rajiv** [comment]
hi. i'm the product manager for Secure CDN (and OCSP stapling) at Akamai. we have been testing OCSP stapling with a limited number of customers, and plan to roll it out to more once ready. OCSP stapling is not generally available for secure properties on Akamai at this time. look for a public announcement on https://community.akamai.com/ later this year.

**Comment by michaelhood** [comment]
hi @rajiv, thanks for commenting. could we discuss over email?

**Comment by rajiv** [comment]
@michaelhood sure!

**Comment by ctaintor** [comment]
@rajiv any updates on this?

**Comment by kylerandolph** [comment]
@rajiv any updates on OCSP stapling?

**Comment by kylerandolph** [comment]
Found [this](https://community.akamai.com/thread/4872-how-to-enable-ocsp-stapling#comment-15960), looks like it's available under certain conditions.

**Comment by rajiv** [comment]
just last week, we enabled OCSP stapling for Akamai-managed certificates. these are certificates where Akamai procures the certificate on behalf of our customers. we will have a public announcement in the next week. 

here's a PR to update the site: https://github.com/igrigorik/istlsfastyet.com/pull/146

**Comment by rajiv** [comment]
SPDY support has been discontinued. see https://community.akamai.com/community/web-performance/blog/2017/02/22/announcing-spdy-end-of-life
